name: tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "main", "reco_updates" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container: seangaz/gradoptics
    steps:
      - name: update env
        run: export ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true

      - name: checkout repository
        uses: actions/checkout@v4

      - name: run pytest
        run: |
          pip install -e .
          pytest -v --tb=native -rA tests/tests.py
