name: tests

on: push

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container: magisslac/magis-docker
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: run pytest
        run: |
          pip install -e .
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pytest -v --tb=native -rA tests/tests.py
